name: helio
dependencies:
  - python==3.7.6
  - numpy==1.17.2
  - matplotlib==3.1.2
  - ipython==7.11.1
  - pip==19.3.1
  - numba==0.45.1
  - scipy==1.3.1
  - scikit-learn==0.20.3
  - scikit-image==0.15.0
  - pandas==0.25.3
  - seaborn==0.9.0
  - astropy==4.0
  - h5py==2.10.0



